{{- if  .Values.hpa_keda   }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  metrics:
  - external:
      metric:
        name: {{ .Values.hpa_keda.metric_name | default "s0-prometheus" }}
        selector:
          matchLabels:
            scaledobject.keda.sh/name: {{ .Release.Name }}
      target:
        averageValue: {{ .Values.hpa_keda.averageValue | default "30" }} 
        type: AverageValue
    type: External
  maxReplicas: {{ .Values.hpa_keda.maxReplicas | default "4" }}
  minReplicas: {{ .Values.hpa_keda.minReplicas | default "2" }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}

{{ end }}
